inherit_gem:
  sbmt-dev: config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  Exclude:
    - spec/internal/pkg/client/**/*

Rails/OverridingEnvVars:
  Exclude:
    - spec/spec_helper.rb
