# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pet_store.proto

require "google/protobuf"

descriptor_data = "\n\x0fpet_store.proto\x12\x0cpet_store.v1\"\x1f\n\x03Pet\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1c\n\x0ePetByIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x99\x01\n\x0bPetResponse\x12\x1e\n\x03pet\x18\x01 \x01(\x0b\x32\x11.pet_store.v1.Pet\x12\x39\n\x08metadata\x18\x02 \x03(\x0b\x32'.pet_store.v1.PetResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32J\n\x04Pets\x12\x42\n\x07PetById\x12\x1c.pet_store.v1.PetByIdRequest\x1a\x19.pet_store.v1.PetResponseB\x1f\xea\x02\x1cPetStore::Grpc::PetStore::V1b\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require "google/protobuf/descriptor_pb"
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = []
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module PetStore
  module Grpc
    module PetStore
      module V1
        Pet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.Pet").msgclass
        PetByIdRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.PetByIdRequest").msgclass
        PetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("pet_store.v1.PetResponse").msgclass
      end
    end
  end
end
