default: &default
  host: localhost
  port: 3000

development:
  <<: *default

test:
  <<: *default

staging:
  host: "<INSERT_YOUR_HOST_HERE>.svc.cluster.local"
  port: 8080

production:
  host: "<INSERT_YOUR_HOST_HERE>.svc.cluster.local"
  port: 8080
