name = "test-app"
version = "0.0.1"

[team]
owner_team = "dex-1"
channel = "dev-ruby-platform"
maintainer_team = "dex-1"
BO = "aleksandr.susikov@sbermarket.ru"

[env]
  [env.APP_NAME]
    type = "string"
    value = "TEST-APP"
    envName = "APP_NAME"
    required = true
